### ISSUE TITLE
set args  --task=md --dataset=DX but can not work corrrectly

### ISSUE THREAD

**Issue by hellostronger** [zhiyuanhubj/UoT#10]
Traceback (most recent call last):
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2024.1.4\plugins\python-ce\helpers\pydev\pydevd.py", line 1551, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2024.1.4\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:\UoT\run.py", line 111, in <module>
    run(args)
  File "D:\UoT\run.py", line 14, in run
    task = get_task(args)
  File "D:\UoT\src\uot\tasks\__init__.py", line 7, in get_task
    return MDTask(args)
  File "D:\UoT\src\uot\tasks\medical_diagnosis.py", line 15, in __init__
    self.data = self.load_dataset(args.dataset)
  File "D:\UoT\src\uot\tasks\medical_diagnosis.py", line 32, in load_dataset
    return json.loads(os.path.join(os.path.dirname(__file__), f"../data/{name}.json").read())
AttributeError: 'str' object has no attribute 'read'

**Comment by dong-river** [comment]
I got the same problem. Are you able to resolve it?

**Comment by AgentDS** [comment]
same question here
